### ISSUE TITLE
How to get the jwt token, and some other envs

### ISSUE THREAD

**Issue by animemandir** [ShivaBhattacharjee/AnimeTrix-next#16]
I havent used jwt ever, how to get one also pls do tell about setting up nodemailer

**Comment by ShivaBhattacharjee** [comment]
You can set up a JWT token via your shell (like Git Bash) by entering:


```ssh
openssl rand -base64 32
```

Regarding Nodemailer, if you're using Gmail as SMTP, you'll need to enable 2FA and use an app password found inside your Google account.
