### ISSUE TITLE
Some anime titles give 404

### ISSUE THREAD

**Issue by animemandir** [ShivaBhattacharjee/AnimeTrix-next#17]
Some anilist ids are not working, like 163134, while 21 works just fine.
the api gives response to all the id queries but the site doesn't show the intended anime.
![image](https://github.com/ShivaBhattacharjee/AnimeTrix-next/assets/78192713/2e457135-aaba-4fe9-b1b1-fb51268b2eb6)

**To Reproduce**
1. Go to 'https://www.animetrix.xyz/details/163134'
2. Now go to  'https://www.animetrix.xyz/details/21'
3. Check consumet api response for each.
4. See error on many ids like 163134,166531,133845

**Expected behavior**
Should give normal anime details page.
`Apr 17, 09:18:35 PM: 2024-04-17T18:18:35.558Z	undefined	INFO	import next server: 254.22ms`
this is what comes up in real time logs

Potential cause could be improper handling of null vales received from api like, but im not sure - 
```json
"title":{"romaji":"Re:Zero kara Hajimeru Isekai Seikatsu 3rd Season",
"english":null,
"native":"Re:ゼロから始める異世界生活 3rd season"},
```

**Comment by ShivaBhattacharjee** [comment]
Data is not available from api end point itself cant do anything in this case

![image](https://github.com/ShivaBhattacharjee/AnimeTrix-next/assets/95211406/d0caf66e-b7cd-4da4-a975-f798c6f0bc65)

**Comment by animemandir** [comment]
Can only consumet api be used incase of such err. like a fallback endpoint.

**Comment by ShivaBhattacharjee** [comment]
Payload is too high in case for consumet api and vercel restricts that so it would just throw a 500 error instead of 404

**Comment by animemandir** [comment]
Also, unrelated to this issue - 
`Collecting page data ...
4:44:16 PM: Something went wrong!
4:44:16 PM: MongoServerError: bad auth : authentication failed
4:44:16 PM:     at Connection.onMessage (/opt/build/repo/node_modules/mongodb/lib/cmap/connection.js:202:26)
4:44:16 PM:     at MessageStream.<anonymous> (/opt/build/repo/node_modules/mongodb/lib/cmap/connection.js:61:60)
4:44:16 PM:     at MessageStream.emit (node:events:517:28)
4:44:16 PM:     at processIncomingData (/opt/build/repo/node_modules/mongodb/lib/cmap/message_stream.js:124:16)
4:44:16 PM:     at MessageStream._write (/opt/build/repo/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
4:44:16 PM:     at writeOrBuffer (node:internal/streams/writable:392:12)
4:44:16 PM:     at _write (node:internal/streams/writable:333:10)
4:44:16 PM:     at Writable.write (node:internal/streams/writable:337:10)
4:44:16 PM:     at TLSSocket.ondata (node:internal/streams/readable:809:22)
4:44:16 PM:     at TLSSocket.emit (node:events:517:28) {
4:44:16 PM:   ok: 0,
4:44:16 PM:   code: 8000,
4:44:16 PM:   codeName: 'AtlasError',
4:44:16 PM:   connectionGeneration: 0,
4:44:16 PM:   [Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' }
4:44:16 PM: }
4:44:16 PM: Something went wrong!`

how do I even connect the db, I made a mongodb.

**Comment by ShivaBhattacharjee** [comment]
paste the mongo db url in .env.local (make sure you have added the ip address else it won't connect)
