### ISSUE TITLE
Register button doesn't work and user can't sign up on your platform

### ISSUE THREAD

**Issue by Harshal-Gahlot** [ShivaBhattacharjee/AnimeTrix-next#23]
**Describe the bug**
The Resister button on /resister page doesn't sign up user or send email.
I tried to find the cause: and noticed there was no request sent in network tab when I click on register button.
When I tried to register through postman, I was successful and got email and was able login through login page.
After inspecting register button, I found it's disabled=true even when I have entered all correct fields which seems root cause.

**To Reproduce**
1. Go to https://www.animetrix.xyz/register
2. fill all details correctly 
3. click on resister button.
4. nothing happens
(May not happen always)

**Expected behavior**
user should get register and get email verification 

**Screenshots**
![image](https://github.com/user-attachments/assets/c7412f01-b775-40c1-8df9-77bc37c11605)

![image](https://github.com/user-attachments/assets/927572db-ff57-4a8e-9156-45ba3a43c124)

![image](https://github.com/user-attachments/assets/93293f09-2bbe-4e71-8cb3-b61940b3c137)
line 108 of https://github.com/ShivaBhattacharjee/AnimeTrix-next/tree/3703077bead603d1b1cfe58c3a7901dae61f0a0a/src/app/register/page.tsx
Also very long line.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: chrome.

**Uff, It took 1.5 for both issues But I hope it makes it easier for you to fix this 😊**

**Comment by ShivaBhattacharjee** [comment]
Thanks for spotting it applied a fix really appreciate it man

**Comment by Harshal-Gahlot** [comment]
Yeah it's FIXED! 🫨 Faster than I could breadth. 👏
