### ISSUE TITLE
Bug: UI breaks on the anime episodes list cards

### ISSUE THREAD

**Issue by mrpvn** [ShivaBhattacharjee/AnimeTrix-next#24]
Describe the bug
Anime title overflow from the anime card.

To Reproduce
Go to https://www.animetrix.xyz/watch/one-piece-episode-1/21
Right side of the screen where all the list of anime ep presents

Screenshots
![Screenshot 2024-09-23 184029](https://github.com/user-attachments/assets/10491a95-29ac-4a60-a293-e654d2505a5f)

Desktop (please complete the following information):
 - OS: Window 11
 - Browser Arc 
 - Version latest

**Comment by Harshal-Gahlot** [comment]
Can I try to fix this? @ShivaBhattacharjee

**Comment by ShivaBhattacharjee** [comment]
Sure feel free assigned you the issue

**Comment by ShivaBhattacharjee** [comment]
Sure feel free assigned you the issue
